/*
 * To Do List API
 *
 * This is a simple todo list API.
 *
 * API version: 0.1.0
 * Contact: jim@anconafamily.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todoclient
// ModelError struct for ModelError
type ModelError struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
