/*
 * To Do List API
 *
 * This is a simple todo list API.
 *
 * API version: 0.1.0
 * Contact: jim@anconafamily.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todoclient
// ModelToDoInput struct for ModelToDoInput
type ModelToDoInput struct {
	Completed bool `json:"completed,omitempty"`
	Order int32 `json:"order,omitempty"`
	Title string `json:"title"`
}
